"""The guide an agent reads before it operates a run in this repo.

Ouroboros runs were driven from the Ouroboros checkout: a human opened the loop
runner's own repo to start, watch and read a run that worked somewhere else.
That put the operator one repo away from the work and made every run a
conversation the project never saw.

The guide this module writes moves the operating knowledge into the target repo,
next to the config and charter it talks about, so an agent opened in the project
already knows a run is possible here, what the last four did, and which command
does what. It is written once by `ouroboros init` and is then the project's own
file: Ouroboros never rewrites it, the way Ouroboros never writes the charter.

`POINTER` is the one line appended to the repo's root `AGENTS.md`/`CLAUDE.md`,
because a file no harness loads by default is a file nobody reads.
"""

from __future__ import annotations

from pathlib import Path

GUIDE_PATH = Path(".ouroboros") / "AGENTS.md"
POINTER = (
    "\n## Unattended runs\n\n"
    "This repo is driven by Ouroboros, an unattended agent loop. Before you start,"
    " stop, or read one, read [`.ouroboros/AGENTS.md`](.ouroboros/AGENTS.md);"
    " past runs are in [`.ouroboros/RUNS.md`](.ouroboros/RUNS.md).\n"
)
POINTER_MARK = "## Unattended runs"

GUIDE = """# Operating Ouroboros in {name}

You are the operator. A human talks to you here, and you start, watch, read and
land unattended runs of this repo. This file is yours and the human's; Ouroboros
does not rewrite it. Keep it true.

## The shape of a run

A run is a loop of iterations against a charter. Each iteration an **actor**
does one unit of work and commits it, and a **critic** reads the change and the
memory, accepts or rejects it, answers as the sleeping user would, and writes
the message the next iteration starts from. When the memory says a reconcile
is due, the actor's next iteration is housekeeping instead of a unit. A
separate maintainer and planner exist but are off unless the config turns them
on. It runs on a branch (`ouroboros/<run>`), inside tmux, for as long as the
charter's stop rules allow.

The human owns exactly one document: `.ouroboros/goal.md`, the charter. No agent
role may write it. Everything else -- the plan, the bets, the record -- is the
loop's.

## What you do, in order

**1. Before a run: read the last one.** `.ouroboros/RUNS.md` is the index and
`.ouroboros/history/<run>.md` is the digest. Read the notes below the marker
first: they are what a human concluded, and they are the only part not derivable
from the logs.

**2. Design or revise the charter.** Use the `ouroboros-design` skill, or edit
`.ouroboros/goal.md` directly. Two rules earn their place here:

- **A done criterion is a claim about the world that one run can make true.**
  A criterion nobody can tick is worse than no criterion: it looks like a target
  and behaves like scenery. If the index shows a run that ticked nothing, suspect
  the charter before you suspect the loop.
- **The horizon ladder is granularity, not time.** Agents have no clock. Never
  write hours, days or weeks in the charter.

**3. Pre-flight, then launch.**

    ouroboros run --for 24h

`run` refuses a dirty tree, so `git status` first -- untracked directories count.
Check the harnesses are authenticated and their usage windows have room; a
subscription window that is nearly full will stall the run rather than fail it.

**4. While it runs**, do not touch the files the loop is working in. A charter
edit applies at the *next* run start, not this one. To watch:

    ouroboros status          # one shot
    ouroboros top             # the live view
    tmux attach -t <session>  # the loop's own output

**5. Reading it.** Use the `ouroboros-checkup` skill. It works mid-run and after,
and it leads with the question the numbers hide: is this moving, or going in
circles?

**6. Stopping and landing it.**

    ouroboros stop            # also writes the run's digest

Then merge with a merge commit -- **never squash a run whose memory cites commit
SHAs** -- and re-run `ouroboros archive` afterwards, because `merged:` is a fact
about the base branch and changes without the run changing.

## The record

| path | who writes it |
|---|---|
| `.ouroboros/goal.md` | the human, alone |
| `.ouroboros/RUNS.md` | generated by `ouroboros archive`; never hand-edit |
| `.ouroboros/history/<run>.md` | generated above the notes marker, **yours below it** |
| `.ouroboros/runs/<run>/` | the loop; gitignored, does not leave this machine |

The digests are the only part of a run that survives its machine, so commit them
with the merge. When a run teaches something -- a charter criterion that could
never close, a model that stalled, a config that wasted a window -- write it
under `## What this taught` in that run's digest. That is what the next
operator, including you, reads first.

## This project

<!-- Fill this in. It is the part no template can write. -->

- **Where runs happen:** (this machine, or a box, and how to reach it)
- **Naming:** (how runs are named, e.g. ot1, ot2, ...)
- **Harnesses and models:** (see `.ouroboros/config.yml`)
- **Green means:** (the exact test command a run must keep passing)
- **Never:** (the things a run must not touch in this repo)
"""


def write_guide(repo: Path, name: str) -> Path | None:
    """Write the operator guide, or leave an existing one alone. Returns what changed."""
    path = repo / GUIDE_PATH
    if path.exists():
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GUIDE.format(name=name))
    return path


def add_pointer(repo: Path) -> list[Path]:
    """Point the repo's own agent contracts at the guide.

    Appended to every root contract that exists, and to `AGENTS.md` when none
    does. A harness loads the root file and nothing else, so a guide with no
    pointer is a guide nobody opens.
    """
    roots = [p for p in (repo / "AGENTS.md", repo / "CLAUDE.md") if p.exists()] or [repo / "AGENTS.md"]
    touched = []
    for path in roots:
        text = path.read_text() if path.exists() else f"# {repo.name}\n"
        if POINTER_MARK in text:
            continue
        path.write_text(text.rstrip() + "\n" + POINTER)
        touched.append(path)
    return touched
